theme = "catppuccin_frappe"

[editor]
cursorline = true
line-number = "relative"
bufferline = "multiple"
rulers = [80, 120]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "â†©"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
H = ["select_mode", "goto_line_start"]
L = ["select_mode", "goto_line_end"]

# esc inspired by https://www.youtube.com/watch?v=aiSI6vdZWgE
esc = ["collapse_selection", "keep_primary_selection"]

# rest inspired by https://www.youtube.com/watch?v=tGYvUXYN-c0
G = "goto_file_end"
X = "extend_line_above"

[keys.normal.space]
q = ":quit"
w = ":write"